language: ruby
services:
  - mysql
  - redis
rvm:
  - 1.9.3
  - 2.0.0
env:
  - SUGAR_DB=sqlite
  - SUGAR_DB=mysql
  - SUGAR_DB=postgresql
matrix:
  exclude:
    - rvm: 1.9.3
      env: SUGAR_DB=sqlite
    - rvm: 1.9.3
      env: SUGAR_DB=postgresql
script:
  - bundle exec rspec spec
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libmagic-dev
before_script:
  - sh -c "if [ '$SUGAR_DB' = 'mysql' ]; then mysql -e 'create database sugar_test;'; fi"
  - sh -c "if [ '$SUGAR_DB' = 'postgresql' ]; then psql -c 'create database sugar_test' -U postgres; fi"
  - sh -c "if [ '$SUGAR_DB' = 'sqlite' ]; then bundle exec rake db:create; fi"
  - rake db:migrate
