# Name of forum
forum_name: BUTT3RSCOTCH
# Short version of forum name (for use on iPhone etc)
forum_short_name: B3S
# HTML formatted version of forum_name
forum_title: BUTT<em>3</em>RSCOTCH

default_domain: butt3rscotch.org
asset_host: http://assets%d.butt3rscotch.org
mail_sender: Butt3rscotch <noreply@butt3rscotch.org>
session_key: _butt3rscotch_session

# Themes
default_theme: b3s
default_iphone_theme: default-iphone

# Enter your API key to enable Flickr integration:
flickr_api: 016918184821edf95505d9acd61e64c4

# Google API key
google_api: ABQIAAAAnWSYmGpYjyofU-RkR7khnxQaLv7OURE2GkMujmXaX4v89Xp-jxTAPesjyBvKHuLc29BxnjWmJa7n9w
google_analytics: UA-8897656-1

# Enable Xbox Live integration
xbox_live_enabled: true

# == PERMISSIONS ==

# Enable public browsing
public_browsing: false

# Enable signups. The invites system will be enabled if this is set to false.
signups_allowed: false

# Signups must be approved by a user admin
signup_approval_required: false
