production:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING
    path: /solr
    auto_commit_after_request: false

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    min_memory: 128M
    max_memory: 2G

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
